spring.datasource.url=jdbc:mysql://localhost/adopet?createDatabaseIfNotExist=true
spring.datasource.username=caio
spring.datasource.password=Caio110@2005

spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=caio
spring.mail.password=Caio110@2005
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
